const assert = require('node:assert/strict');
process.env.TZ = 'Europe/Zurich';
const core = require('../extension/editions-core.js');
const at = value => core.windowAt(new Date(value).getTime());
assert.equal(at('2026-10-07T07:59:59').label, 'Evening');
assert.equal(new Date(at('2026-10-07T07:59:59').startsAt).getDate(), 6);
assert.equal(at('2026-10-07T08:00:00').label, 'Morning');
assert.equal(at('2026-10-07T13:00:00').label, 'Afternoon');
assert.equal(at('2026-10-07T18:00:00').label, 'Evening');
assert.equal(new Date(at('2026-10-07T18:00:00').nextAt).getHours(), 8);
assert.equal(new Date(at('2026-03-29T01:00:00').nextAt).getHours(), 8, 'Spring DST keeps the local morning window');
assert.equal(new Date(at('2026-10-25T01:00:00').nextAt).getHours(), 8, 'Autumn DST keeps the local morning window');
const item = id => ({tweet_results:{result:{rest_id:String(id),legacy:{full_text:'Fixture'},core:{user_results:{result:{rest_id:'user'}}}}}});
const entry = id => ({entryId:`tweet-${id}`,sortIndex:String(1000-id),content:{entryType:'TimelineTimelineItem',itemContent:item(id)}});
const payload = entries => ({data:{home:{home_timeline_urt:{instructions:[{type:'TimelineAddEntries',entries}]}}}});
const ad = entry(900);ad.content.itemContent.promotedMetadata={advertiser:'fixture'};
const moduleEntry={entryId:'conversation',content:{entryType:'TimelineTimelineModule',items:[{entryId:'nested-1',item:{itemContent:item(101)}},{entryId:'cursor',item:{itemContent:{cursorType:'Bottom',value:'escape'}}}],showMore:{cursor:'escape'},metadata:{}}};
const source=payload([ad,entry(0),entry(0),moduleEntry,...Array.from({length:60},(_,i)=>entry(i+1)),{entryId:'cursor-bottom',content:{cursorType:'Bottom',value:'NEXT'}}]);
const before=JSON.stringify(source);
const frozen=core.freeze(source);
assert.equal(frozen.count,40);
assert.equal(JSON.stringify(source),before,'Freezing does not mutate X’s response');
const entries=core.freeze(source).payload.data.home.home_timeline_urt.instructions[1].entries;
assert.equal(entries[0].entryId,'tweet-0');assert.equal(entries[0].sortIndex,'1000');
assert.equal(entries[1].content.items.length,1);assert.equal(entries[1].content.showMore,undefined);
assert.ok(!JSON.stringify(frozen.payload).includes('NEXT'));assert.ok(!JSON.stringify(frozen.payload).includes('escape'));
assert.equal(core.empty(frozen.payload).data.home.home_timeline_urt.instructions.length,2,'Cursor requests finish without repeating posts');
assert.throws(()=>core.freeze({data:{}}));
assert.equal(core.freeze(payload([])).count,0,'An empty valid feed is a valid edition');
assert.equal(core.operation('https://x.com/i/api/graphql/query/HomeLatestTimeline','https://x.com'),'following');
assert.equal(core.operation('https://elsewhere.test/i/api/graphql/query/HomeLatestTimeline','https://x.com'),null);
assert.equal(core.operation('https://x.com/i/api/graphql/query/CreateTweet','https://x.com'),null);
const request={method:'POST',body:JSON.stringify({variables:{count:99,cursor:'OLD',seenTweetIds:['a']},features:{preserve:true},queryId:'query'}),headers:{authorization:'TEST_ONLY'}};
const next=core.request('https://x.com/i/api/graphql/query/HomeLatestTimeline',request);
assert.deepEqual(JSON.parse(next.init.body),{variables:{count:40},features:{preserve:true},queryId:'query'});
assert.equal(JSON.parse(request.body).variables.cursor,'OLD');
assert.equal(core.hasCursor('https://x.com/a',request),true);
const like=core.reaction('https://x.com/i/api/graphql/query/FavoriteTweet',JSON.stringify({variables:{tweet_id:'0'}}),'https://x.com');
assert.deepEqual(like,{tweetId:'0',field:'favorited',enabled:true});
const originalRecord={payload:payload([entry(0)])};originalRecord.payload.data.home.home_timeline_urt.instructions[0].entries[0].content.itemContent.tweet_results.result.legacy.favorite_count=2;
const liked=core.applyReaction(originalRecord,like);const legacy=liked.payload.data.home.home_timeline_urt.instructions[0].entries[0].content.itemContent.tweet_results.result.legacy;assert.equal(legacy.favorited,true);assert.equal(legacy.favorite_count,3);assert.equal(core.applyReaction(liked,like).payload.data.home.home_timeline_urt.instructions[0].entries[0].content.itemContent.tweet_results.result.legacy.favorite_count,3,'Repeated success does not count twice');
assert.equal(originalRecord.payload.data.home.home_timeline_urt.instructions[0].entries[0].content.itemContent.tweet_results.result.legacy.favorited,undefined);
assert.equal(core.lastTweetId(payload([entry(7)])),'7');
console.log('Edition schedule, DST, native entry preservation, module bounds, ad exclusion, immutable capture, cursor termination and request scope passed.');
module.exports={payload,entry};
