const assert = require('node:assert/strict');
const core = require('../extension/replies-core.js');
const tweet = id => ({rest_id:String(id),legacy:{full_text:'Fixture post'},core:{user_results:{result:{core:{name:'Author'}}}}});
const item = id => ({tweet_results:{result:tweet(id)}});
const post = id => ({entryId:`tweet-${id}`,content:{itemContent:item(id)}});
const ad = post('ad');ad.content.itemContent.promotedMetadata={advertiser:'fixture'};
const prefixAd = post('prefix-ad');prefixAd.entryId='promoted-tweet-prefix';
const nested = {entryId:'home-conversation-thread',content:{items:[{item:{itemContent:item('nested-1')}},{item:{itemContent:item('nested-2')}},{item:{itemContent:{tweet_results:{result:{__typename:'TweetTombstone'}}}}}]}};
const retweet = post('retweet');retweet.content.itemContent.tweet_results.result.legacy.retweeted_status_result={result:tweet('original')};
const wrapped = post('wrapped');wrapped.content.itemContent.tweet_results.result={__typename:'TweetWithVisibilityResults',tweet:tweet('wrapped')};
const payload={data:{home:{home_timeline_urt:{instructions:[{type:'TimelineAddEntries',entries:[...Array.from({length:70},(_,i)=>post(i)),ad,prefixAd,nested,retweet,wrapped,{entryId:'cursor-bottom',content:{cursorType:'Bottom',value:'NEXT'}}]}]}}}};
const before=JSON.stringify(payload);
const read=core.readHome(payload);assert.ok(read.valid);assert.equal(read.cursor,'NEXT');
assert.ok(!read.replies.some(r=>['ad','prefix-ad','retweet'].includes(r.id)));
assert.ok(read.replies.some(r=>r.id==='nested-1'));assert.ok(read.replies.some(r=>r.id==='nested-2'));
assert.equal(read.replies.find(r=>r.id==='original').repostedBy,'Author');
assert.ok(read.replies.some(r=>r.id==='wrapped'));
const rows=core.merge([],read.replies);assert.equal(rows.length,60);
assert.equal(core.merge(rows,read.replies).length,60);
for(let page=1;page<=6;page++)assert.equal(rows.slice((page-1)*10,page*10).length,10);
const stripped=core.readHome(core.shapeHome(payload));assert.equal(stripped.replies.length,0);assert.equal(stripped.cursor,null);
assert.ok(core.homeTimeline(core.shapeHome(payload)).instructions.some(i=>i.type==='TimelineTerminateTimeline'&&i.direction==='Top'));
assert.equal(JSON.stringify(payload),before);
assert.equal(core.readHome({data:{}}).valid,false);assert.equal(core.shapeHome({data:{}}),null);
const cursorBatch={data:{home:{home_timeline_urt:{instructions:[{type:'TimelineReplaceEntry',entry:{entryId:'cursor-bottom',content:{cursorType:'Bottom',value:'NEW'}}}]}}}};assert.equal(core.readHome(cursorBatch).cursor,'NEW');
console.log('Home: organic posts, ads excluded, modules, repost attribution, wrapped tweets, exact 10/page, 60-post cap, deduplication, removed infinite cursors, immutable payloads, and invalid schemas passed.');
